### PR TITLE
Blockquote - New markup, new SASS

### LINKED ISSUE #99: ACF Block: Blockquotes
We need to create a block to implement the block quote styles [shown in the XD](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/screen/1875d326-6870-4bd0-b2d7-3d41b592470a/) and on [Storybook](https://unity.web.asu.edu/@asu-design-system/bootstrap4-theme/?path=/docs/components-blockquotes--default).

This block is already in development, and I'll assign it to Justin upon creation.

### PR DESCRIPTION
**Pull request by SteveRyan-ASU**
Resolves #99

Added `/blocks/blockquote-v2.scss` as a source file for the new markup for blockquotes. The included file does a "reset" of the existing blockquote rules that ship from the UDS-Bootstrap project, so it'll be safe to use moving forward.

### CODE REVIEW

**Comment by SteveRyan-ASU** [comment]
Base quote with the accent colors turned maroon. (Default is gray-7.)
```
<figure class="uds-blockquote accent-maroon">
    <svg title="Open quote" role="img" aria-labelledby="open-quote-title" viewBox="0 0 302.87 245.82">
        <title id="open-quote-title">Open quote</title>
        <path
            d="M113.61,245.82H0V164.56q0-49.34,8.69-77.83T40.84,35.58Q64.29,12.95,100.67,0l22.24,46.9q-34,11.33-48.72,31.54T58.63,132.21h55Zm180,0H180V164.56q0-49.74,8.7-78T221,35.58Q244.65,12.95,280.63,0l22.24,46.9q-34,11.33-48.72,31.54t-15.57,53.77h55Z" />
    </svg>
    <blockquote>
        <p>We hold these truths to be self-evident, that all men are created equal, that they are endowed by
            their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of
            Happiness.</p>
    </blockquote>
    <figcaption>
        <cite class="name">Thomas Jefferson</cite>
        <cite class="description">The Declaration of Independence</cite>
    </figcaption>
</figure>
```
Added the `.with image` class and changed the accent color to gold.
```
<figure class="uds-blockquote accent-gold with-image">
    <img src="https://placeimg.com/400/400/any" alt="Pretend this is Michael M. Crow, President of ASU" />
    <blockquote>
        <p>ASU is a comprehensive public research university, measured not by whom we exclude, but rather by
            whom we include and how they succeed; advancing research and discovery of public value; and assuming
            fundamental responsibility for the economic, social, cultural and overall health of the communities
            it serves.</p>
    </blockquote>
    <figcaption>
        <cite class="name">Michael M. Crow</cite>
        <cite class="description">ASU Charter</cite>
    </figcaption>
</figure>
```
Features the `.reversed` class.
```
<figure class="uds-blockquote with-image reversed">
    <img src="https://placeimg.com/300/300/any" alt="Pretend this is Michael M. Crow, President of ASU" />
    <blockquote>
        <p>Eight design aspirations guide the ongoing evolution of ASU as a New American University. These
            institutional objectives are integrated in innovative ways throughout the university to achieve
            excellence, access and impact.</p>
    </blockquote>
    <figcaption>
        <cite class="name">Michael M. Crow</cite>
        <cite class="description">ASU Charter</cite>
    </figcaption>
</figure>
```

**Comment by wmcconnell** [comment]
I've cleaned up the code and comments and tested this locally. Works like a charm. Since I ended up working on this one, I'll hold off on reviewing/approving and add some others to the list so that people can pull down this branch and try it out.

**Review by zainabD — CHANGES_REQUESTED** [review]
Here is some suggestions and issues I found: 
- [ ] [Issue] since we only accept 180px images, I would add this css to image in order to fix the issues with images that are not 180x180 
```
object-fit: cover;
height: 180px;
```
image

- [ ] [Issue] the image lines up with the bottom edge of the text when we have longer text:
image

- [suggestion] I noticed that the quotes with no style have no padding while the ones with styles get a 1.5rem of padding around, I would either remove the padding from all or add padding to all quotes to make them all line up in case if we have multiple quotes. 
image

**Comment by nathan-rollins** [comment]
I have a follow-on suggestion for the images. If 180x180 is a standard size that we should enforce, then that would be a good candidate to set as an image size preset in WP. That way, uploaded images will automatically have a 180x180 version auto-generated (would WP auto-crop off-ratio images in that case?)

If this worked, rather than changing the apparent size of the image, we might be able to program the image Blocks to only use the correct image preset.

**Review by zainabD — APPROVED** [review]

**Review by earlalex — APPROVED** [review]

**Pull request merged**
