### PR TITLE
Multi-Button Heroes and Hero Image Alt Tags

### PR DESCRIPTION
**Pull request by wmcconnell**
Updates the Hero Image field group and associated code to allow for the multiple buttons we need for the SFIS (and other) degree pages. Also includes a small update to allow for `alt` tags on the hero image (now that we are using actual image tags, and not CSS background images).

Changes proposed in this pull request:

- Update the Page Hero field group to include a new repeater field that repeats clones of the button field group, allowing users to enter an arbitrary amount of buttons in the hero area.
- Update the corresponding code to loop through that repeater field and render buttons. Added new code to handle the additional button values that the original fields did not include.
- Update the Page Hero field group to read the hero image as an array of data, and not just the URL to the image, so we can grab the `alt` or `description` values.
- Update the corresponding image tag code to include the `alt` value
- Maintain the original button fields for backwards compatibility (to be removed in a future update). The new hero will only fall back on the old button fields if there are no buttons in the new repeater field.

Changes **not** included here:

- Video heroes. Working on that one for a later update
- Full EWWW type support for `srcset` and WebP images for the hero. I believe we will need to replicate whatever EWWW does, since we are rendering our own `` tag here, and not using a block, or other WordPress technique, to insert the image on the page. That will also come in a future update once I take a look at the output of existing images.

### CODE REVIEW

**Review by zainabD — CHANGES_REQUESTED** [review]
Can we remove the padding from the hero description: 
Screen Shot 2021-03-30 at 1 17 45 PM

- I noticed that the Single Word Highlight checking method is case sensitive, when typing the word in small letters we will get the error: 
`Notice: Undefined variable: title_string in /app/wp-content/themes/UDS-WordPress-Theme/templates-global/hero.php`
Can we add a message saying that this is case sensitive or maybe not accepting any values if don't match.
image

**Comment by zainabD** [comment]
Screen Shot 2021-03-30 at 3 19 14 PM

**Comment by zainabD** [comment]
This should also fix the issue #144

**Comment by wmcconnell** [comment]
I've updated the Hero content area (title, text, buttons) to wrap it in a plain `container`, which seems to make it behave like an expected Bootstrap row/column.

**Review by zainabD — DISMISSED** [review]

**Comment by wmcconnell** [comment]
Added one more fix: Justin noticed that heroes without any buttons were having their titles moved down to the very bottom of the hero image. This was a result of a `margin-bottom: -2rem;` being applied to the content area. I updated our code to apply a particular class of `.has-buttons` when there are any buttons, and we target that more specific selector for the negative margin. I then add a margin to the bottom and left of the title when it's there by itself.

**Pull request merged**
