### PR TITLE
ACF Block - Content Image Overlap

### PR DESCRIPTION
**Pull request by SteveRyan-ASU**
This PR adds a new block to the theme as well as the necessary SASS to support the design. The block design can be found within the [XD document](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/screen/674ebe9d-bcfd-48c9-a3eb-37efe95f4f4a/specs/) under the "Miscellaneous content sections" heading. The specific design is labeled there as "Content Image Overlap"

The CSS rules for block layout aren't currently included in the UDS-Bootstrap package. So, instead I created a place for that SASS to be compiled into the theme at `/sass/blocks/_image-overlap.scss` That file is directly compiled by the "root" `theme.scss` file.

The block contains two ACF fields (background image + content left/right) and utilizes `<InnerBlocks />` as the primary way to enter content into the designated content well. The allowed blocks within this block have been limited to the following:

- headline
- paragraph
- custom HTML
- list
- separator

Eventually, I can see that we might want to add the following additional ACF blocks to the allowed list once they are completed. 

- ACF Button
- ACF Blockquote

### CODE REVIEW

**Comment by SteveRyan-ASU** [comment]
Images from the Gutes. :-) 
image

**Comment by SteveRyan-ASU** [comment]
When merged, this will close #100.

**Review by wmcconnell — CHANGES_REQUESTED** [review]
First of all, I love this block. The CSS grid stuff is cool, and we'll be taking that approach with other blocks as well. Also, `<InnerBlocks \>` is the best. Nicely done! I worked one of these blocks into a container with a background image, however, and discovered that the content area loses its background color at mobile sizes. 

Here's a block looking nice at desktop size:

cio-desktop

But at mobile size, the content area is transparent:

cio-mobile

**Comment by wmcconnell** [comment]
I should add that applying a background color to `.content-wrapper` did the trick. There is some massaging to do with padding/margin, however, so I left it to you to determine if that's a grid thing.

**Comment by wmcconnell** [comment]
I pushed some changes that appear to fix the display on mobile. I added a background color of default white, and the same padding as the desktop version. Here is a new example at desktop:

Screen Shot 2021-02-16 at 10 38 57 AM

And here it is at mobile size, with the new styling applied:

Screen Shot 2021-02-16 at 10 39 10 AM

**Review by wmcconnell — APPROVED** [review]

**Comment by wmcconnell** [comment]
I also approved those changes (since my initial concerns are addressed by this update). If it looks good to @SteveRyan-ASU, I'll merge this as our first block in the actual theme!

**Comment by SteveRyan-ASU** [comment]
I'm assigned as the owner of the PR and therefore can't officially "approve." But @wmcconnell's latest additions being the component into complete alignment with the XD document.

Approved. (Thanks for the fix Walt!)

**Pull request merged**
